### PR TITLE
update rollbar snippet

### PR DESCRIPTION
**Pull request by and-megan**
@coryvirok is there anything else that needs to be updated here? The change is v1.9 to v2.2.0

### CODE REVIEW

**Comment by idostern** [comment]
@and-megan can this be updated to the latest version 2.2.8 I'm really waiting for this

**Comment by idostern** [comment]
Who’s merging this?

**Comment by and-megan** [comment]
Hey @hankim813 I noticed you released the last version so I thought I'd reach out. https://circleci.com/gh/segment-integrations/analytics.js-integration-rollbar/332 Looks like a Slack/Circle issue - any thoughts?

**Comment by hankim813** [comment]
hi @and-megan sorry for the late reply. Are there any breaking changes from v1 to v2? Want to make sure we dont need to update any other code in this integration. 

With that said, can you link us to the changelog from v1 to v2 for our own documentation purposes?

**Comment by and-megan** [comment]
Hey @hankim813 thanks for checking in! Here's the Changelog https://github.com/rollbar/rollbar.js/blob/master/CHANGELOG.md

Scope is the only *breaking* change, but there is a bit of difference in how some details of capture uncaught exceptions work and probably larger than just rollbar-browser doesn’t exist anymore.

**Comment by ccnixon** [comment]
Hi everyone - we're looking into this now and should have a fix shipped tomorrow.

**Comment by ccnixon** [comment]
Hi everyone - quick update here. It took a bit longer to get the new sdk version working. We have a pull request ready but are going to deploy tomorrow morning instead. Apologies for the delay and thanks for your patience. 

Here is the PR: https://github.com/segment-integrations/analytics.js-integration-rollbar/pull/18

Thanks @and-megan and @idostern for your help! Will close this out.

**Pull request closed without merging**
